CREATE DATABASE SoftUni

CREATE TABLE Towns
(
   Id BIGINT PRIMARY KEY IDENTITY,
   [Name] NVARCHAR(200) NOT NULL
)

CREATE TABLE Addresses
(
   Id BIGINT PRIMARY KEY IDENTITY,
   AddressText NVARCHAR(300) NOT NULL,
   TownId BIGINT NOT NULL
)

CREATE TABLE Departments
(
   Id BIGINT PRIMARY KEY IDENTITY,
   [Name] NVARCHAR(200) NOT NULL
)

CREATE TABLE Employees
(
   Id BIGINT PRIMARY KEY IDENTITY,
   FirstName NVARCHAR(30) NOT NULL,
   MiddleName NVARCHAR(50) NOT NULL,
   LastName NVARCHAR(50) NOT NULL,
   JobTitle  NVARCHAR(50) NOT NULL, 
   DepartmentId BIGINT NOT NULL, 
   HireDate DATETIME2, 
   Salary DECIMAL(20,2), 
   AddressId BIGINT NOT NULL
)


ALTER TABLE Addresses
ADD FOREIGN KEY (TownId) REFERENCES Towns(ID); 


ALTER TABLE Employees
ADD FOREIGN KEY (DepartmentId) REFERENCES Departments(ID); 


ALTER TABLE Employees
ADD FOREIGN KEY (AddressId) REFERENCES Addresses(ID);